services:
  linx_api:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    environment:
      PORT: 8000
    env_file: .env
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ./:/linx/
    networks:
      - linx_network
    depends_on:
      linx_db:
        condition: service_healthy
  linx_db:
    image: postgres:16
    container_name: ${DB_CONTAINER_NAME}
    environment:
      PGDATA: /var/lib/postgresql/data/${DB_CONTAINER_NAME}/
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_SCHEMA: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    networks:
      - linx_network
    volumes:
      - ${DB_VOLUME_FOLDER}:/var/lib/postgresql/data/${DB_CONTAINER_NAME}
    command: -p ${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p $${POSTGRES_PORT}"]
      interval: 2s
      timeout: 2s
      retries: 10
networks:
  linx_network:
    name: linx_network
    external: false