"""Create searches table

Revision ID: 4d4354ebfaf2
Revises: 848a8a7f700b
Create Date: 2024-09-03 01:18:59.212256

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '4d4354ebfaf2'
down_revision = '848a8a7f700b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('search', sa.VARCHAR(length=150), nullable=False, comment='search query'),
    sa.Column('city', sa.VARCHAR(length=150), nullable=False, comment='actual city name'),
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('rm_timestamp', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_searches')),
    sa.UniqueConstraint('created_on', 'rm_timestamp', name=op.f('uq_searches_created_on'))
    )
    op.create_index(op.f('ix_searches_searches_city'), 'searches', ['city'], unique=False)
    op.create_index(op.f('ix_searches_searches_pk'), 'searches', ['pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_searches_searches_pk'), table_name='searches')
    op.drop_index(op.f('ix_searches_searches_city'), table_name='searches')
    op.drop_table('searches')
    # ### end Alembic commands ###
