"""Create weather table

Revision ID: 848a8a7f700b
Revises: 
Create Date: 2024-09-03 00:25:19.822517

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '848a8a7f700b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('city', sa.VARCHAR(length=150), nullable=False, comment='city name'),
    sa.Column('forecast_date', sa.DateTime(), nullable=False, comment='date for the weather forecast'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='temperature in celsius'),
    sa.Column('wind', sa.Float(), nullable=False, comment='wind speed'),
    sa.Column('cloudiness', sa.VARCHAR(length=150), nullable=False, comment='cloudiness description'),
    sa.Column('pressure', sa.SmallInteger(), nullable=False, comment='pressure in hpa'),
    sa.Column('humidity', sa.SmallInteger(), nullable=False, comment='humidity percentage'),
    sa.Column('sunrise', sa.TIMESTAMP(), nullable=False, comment='sunrise timestamp'),
    sa.Column('sunset', sa.TIMESTAMP(), nullable=False, comment='sunset timestamp'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='latitude coordinates'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='longitude coordinates'),
    sa.Column('pk', sa.BigInteger(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('rm_timestamp', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_weather')),
    sa.UniqueConstraint('city', 'forecast_date', 'rm_timestamp', name=op.f('uq_weather_city'))
    )
    op.create_index(op.f('ix_weather_weather_city'), 'weather', ['city'], unique=False)
    op.create_index(op.f('ix_weather_weather_forecast_date'), 'weather', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_weather_weather_pk'), 'weather', ['pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_weather_pk'), table_name='weather')
    op.drop_index(op.f('ix_weather_weather_forecast_date'), table_name='weather')
    op.drop_index(op.f('ix_weather_weather_city'), table_name='weather')
    op.drop_table('weather')
    # ### end Alembic commands ###
